site_name: 张均的笔记
pages:
    - index : index.md
    - 微服务 :
        - netflix : microservice.md
        - restfulApi规范 : restfulapi.md
        - feign使用问题 : feign-problem.md
    - 设计模式 : designPattern.md
    - docker : 
        - docker基础 : docker.md
        - docker-mysql : mysql-docker.md
        - docker-nginx : nginx.md
    - java :
        - 多线程 : thread.md
        - lambda : lambda.md
        - JSR310-日期 : JSR310.md
        - jvm及GC : gc.md
        - swagger : swagger.md
        - 令牌桶 : limiting.md
        - 代理(字节码) : javassit.md
    - 数据库 :
        - db事务 : trans.md
        - 连接池 : dbpool.md
    - spring :
        - springboot : springboot.md
        - springcontext: context.md
#theme: readthedocs